added conference tag
kryonknowledgeworks/jats-xml-to-html-parser pull request #24
Opened 2024-10-05 12:01 UTC by KathiresanTechnoKryon

2024-10-05 12:46 UTC, alwintechnokryon approved these changes

2024-10-09 12:07 UTC, muthukumarTechno requested changes

2024-10-09 12:07 UTC, muthukumarTechno commented on src/main/java/com/kryonknowledgeworks/jats2html/JATS2HTMLParser.java
> +        System.out.println( parse("D:\\AADNIC-2019-KRYON\\XML\\AADNIC-2019-120.xml","D:\\AADNIC-2019-KRYON\\XML",false));
remove print

2024-10-09 12:16 UTC, muthukumarTechno submitted a review, later dismissed

2024-10-10 06:59 UTC, merged